#!/bin/bash

bat=`acpi | cut -d ' ' -f3-5 | sed -e "s/,//g;s/Discharging/ /g;s/Charging/ /g;s/Full/ /g;s/Unknown/ /g;s/ 0*/ /g;s/ :/ /g"`

val=${bat:2}
val=${val%%%*}

echo "$bat"
# echo "$val"
echo ""
if [ $val -gt 60 ]; then
        echo "#00FE66"
elif [ $val -gt 30 ]; then
        echo "#FF6000"
else
        echo "#FF0100"
fi
