#!/bin/bash

# silent_bell=
# bell=
bell=🔔
silent_bell=🔕

if [ $BLOCK_BUTTON ] && [ $BLOCK_BUTTON -eq 1 ]; then
        toggle_notify
fi

if [ -f /tmp/dnd ]; then
        echo "$silent_bell"
        echo ""
        echo "#FF5000"
else
        echo "$bell"
        echo ""
        echo "#00FF00"
fi
