#!/bin/sh

awk 'BEGIN{
    printf "\n  "
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    maxcol=62;
    maxrow=5;
    for (rowno=0; rowno<maxrow; rowno++) {
        for (colnum = 0; colnum<maxcol; colnum++) {
            r = 255-(colnum*255/(maxcol-1));
            g = (colnum*510/(maxcol-1));
            b = (colnum*255/(maxcol-1));
            if (g>255) g = 510-g;
            printf "\033[48;2;%d;%d;%dm", r,g,b;
            printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
            if (rowno%2==0)
                printf "%s\033[0m", substr(s,colnum+1,1);
            else
                printf "%s\033[0m", substr(s,colnum+2,1);
        }
        printf "\n  ";
    }
    printf "\n"
}'
