#    _               _             _ _                     
#   | |__   __ _ ___| |__     __ _| (_) __ _ ___  ___  ___ 
#   | '_ \ / _` / __| '_ \   / _` | | |/ _` / __|/ _ \/ __|
#  _| |_) | (_| \__ \ | | | | (_| | | | (_| \__ \  __/\__ \
# (_)_.__/ \__,_|___/_| |_|  \__,_|_|_|\__,_|___/\___||___/

alias v='vim'
alias a='sudo apt'
alias nano='nano -$'
alias py='python3'
alias clr_cache='sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches"'
alias mycodes='cd /media/$USER/F/mycodes'
