# Sample .bashrc for SuSE Linux
# Copyright (c) SuSE GmbH Nuernberg

# There are 3 different types of shells in bash: the login shell, normal shell
# and interactive shell. Login shells read ~/.profile and interactive shells
# read ~/.bashrc; in our setup, /etc/profile sources ~/.bashrc - thus all
# settings made here will also take effect in a login shell.
#
# NOTE: It is recommended to make language settings in ~/.profile rather than
# here, since multilingual X sessions would not work properly if LANG is over-
# ridden in every subshell.

# Some applications read the EDITOR variable to determine your favourite text
# editor. So uncomment the line below and enter the editor of your choice :-)
#export EDITOR=/usr/bin/vim
#export EDITOR=/usr/bin/mcedit

# For some news readers it makes sense to specify the NEWSSERVER variable here
#export NEWSSERVER=your.news.server

# If you want to use a Palm device with Linux, uncomment the two lines below.
# For some (older) Palm Pilots, you might need to set a lower baud rate
# e.g. 57600 or 38400; lowest is 9600 (very slow!)
#
#export PILOTPORT=/dev/pilot
#export PILOTRATE=115200

# test -s ~/.alias && . ~/.alias || true


# cd with only dir
shopt -s autocd

PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

[ -f ~/.config/bash/aliases ] && source ~/.config/bash/aliases
[ -f ~/.config/less/lessrc ] && source ~/.config/less/lessrc
[ -f ~/bin/lsx ] && source ~/bin/lsx
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -f /media/$USER/F/Rust/cargo/env  ] && source "/media/$USER/F/Rust/cargo/env"

# PATH="$PATH:/media/$USER/F/node/bin"
# PATH="$PATH:/media/gourish/F/go/bin"
# PATH="$PATH:/media/gourish/F/jdk-17/bin"
# export PATH

# Prompt
# PS1='\[\033[1m\]\[\033[01;34m\][\[\033[01;36m\]\u\[\033[01;33m\]@\[\033[01;32m\]\h \[\033[01;35m\]\W\[\033[01;31m\]]\[\033[00m\]\$ '

# $HOME/.scripts/cowsay_wrapper
$HOME/.scripts/term_art/alpha
source /usr/share/blesh/ble.sh -o keymap_vi_mode_show=
