#!/bin/sh

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width    3
bspc config window_gap      6

bspc config split_ratio             0.5
bspc config single_monocle          false
bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config gappless_monocle        true

bspc config focussed_border_color   "#BD93F9"
bspc config normal_border_color     "#282A36"
bspc config active_border_color     "#8BE9FD"
bspc config presel_feedback_color   "#50FA7B"

sh $HOME/.config/X11/xprofile
