#!/bin/bash

dmenu -v 1>/dev/null 2>/dev/null || exit 0

function launch_configs {
    conf_path=/home/$USER/.config
    # config=$(ls -a $conf_path | grep -E '^\.' | dmenu -l)
    while true
    do
        config=$(ls -a $conf_path | grep -vE '^\.$' | dmenu -l 10 -p '~~ to exit')
        [ $config == '~~' ] && return 0
        conf_path=$conf_path/$config
        [ -d $conf_path ] || break
    done
    $TERMINAL -e $EDITOR $conf_path
    return 0
}

function launch_scripts {
    script_path=/home/$USER/.scripts
    while true
    do
        script=$(ls -a $script_path | grep -vE '^\.$' | dmenu -l 10 -p '~~ to exit')
        [ $script == '~~' ] && return 0
        script_path=$script_path/$script
        [ -d $script_path ] || break
    done
    $TERMINAL -e $EDITOR $script_path
    return 0
}


[ $# -eq 0 ] && echo "conf_script_launcher [configs|scripts]" && exit 0
TERMINAL=${TERMINAL=terminator}
file_type=$1

if [ $file_type == 'configs' ]; then
    launch_configs
elif [ $file_type == 'scripts' ]; then
    launch_scripts
else
    echo "Wrong File Type Option"
    echo "conf_script_launcher [configs|scripts]"
fi
