#!/bin/bash

pgrep snapwmbar > /dev/null

if [[ $? -eq 0 ]]; then
    kill $(pstree -lp | grep -E snapwmbar.+sleep | sed "s/.*sleep(\([0-9]\+\)).*/\1/")
else
    arg=$1
    pgrep polybar > /dev/null && polybar=1 || polybar=0

    if [ $polybar -eq 1 ]; then
        case $arg in
            2) polybar-msg hook backlight 1
            ;;
            3) polybar-msg hook dnd 1
            ;;
            4) polybar-msg hook volspk 1
            ;;
            5) polybar-msg hook volmic 1
            ;;
        esac
    else
        pgrep i3blocks > /dev/null && bar=i3blocks || bar=lemon
        pkill -x -SIGRTMIN+$arg $bar
    fi
fi
